### PR TITLE
Checking in the pods folder and updating the Git Ignore to not ignore the pods.

### PR DESCRIPTION
**Pull request by alexrrouse**
This is checking in the pods dir for the example project.

### CODE REVIEW

**Comment by arrouse** [comment]
@ZevEisenberg @KingOfBrian For #54

**Comment by ndonald2** [comment]
Wait, what? Why? The podfile references this exact repo. You've just checked in the source code for RZVinyl in a subdirectory... this is completely redundant.

**Comment by ndonald2** [comment]
In otherwords, RZVinyl now contains its own source code twice, for no reason. And it's likely to fall out of date as things are committed.

**Comment by ZevEisenberg** [comment]
@ndonald2 I think this is a quirk about how this repo is set up. See, for example, the https://github.com/Raizlabs/BonMot repo (shameless plug): It has its Pods directory checked in, but doesn't have the source code twice.

**Comment by ndonald2** [comment]
Ah my bad, it's just the headers, not the source files. But I still don't understand why the pods directory needs to be checked in. Is it so users who don't use cocoapods can build the example?

**Comment by ZevEisenberg** [comment]
Yes, but it also helps to validate that the example project is building and working correctly. Related: If we are going to merge this PR, we should delete this section from the Makefile:

```ruby
task :pods do
  sh("rm -f Example/Podfile.lock")
  sh "rm -rf Example/Pods"
  sh("rm -rf Example/*.xcworkspace")
end
```

And possibly also the `pod install` part.

**Comment by ndonald2** [comment]
> it also helps to validate that the example project is building and working correctly

How so? I would have thought that installing the pods before a CI build would be sufficient for this. Sorry for all the meddling, I'm just curious what the rationale is.

**Comment by ZevEisenberg** [comment]
I guess I figured more about it working on the developer's machine. You're right that running it on CI can also validate that. I think this is more a "feels right" than "is empirically right" kind of argument - and I hate arguments like that :smile:

**Comment by ndonald2** [comment]
Sure thing, if it feels right to the team then by all means it's worth doing. My only concern is the lack of DRYness – if this gets merged, commits from here on out will need to make sure to include any changes to the pods directory, lest they go out of sync.

**Comment by ndonald2** [comment]
By necessity, that means running `pod update` before committing, which serves the same purpose for validating the example project on the dev machine. There's no way to have up-to-date an up-to-date pods directory for the example project without running `pod` commands anyway.

**Comment by jwatson** [comment]
@arrouse @ZevEisenberg if you're OK with this, let's merge it. Otherwise we should close the PR.

**Comment by ZevEisenberg** [comment]
Still need to clean up the Makefile. And why is the build failing?

**Pull request closed without merging**
