### PR TITLE
Added limit calls to `rzv_where:...`

### PR DESCRIPTION
**Pull request by dostrander**
- Added limit parameter call to `rz_where:...` calls from `NSManagedObject`
- Added baseline tests for limit

### CODE REVIEW

**Comment by jwatson** [comment]
Nice idea. It'd be good to have a constant that represents “no limit” instead of passing the `0` literal. Possible names include `RZVNoLimit`, `RZVNoFear`, and `RZVGottaCatchEmAll`.

**Comment by mr-fixit** [comment]
If you're adding `limit`, shouldn't `offset` come along for the ride?  I can see how the former is useful by itself, so I'd go ahead without `offset`.

**Comment by KingOfBrian** [comment]
Yea, doing this without the `offset` is a bit weird. And then objective-c does this awesome thing where the number of methods required becomes insane. 

Adding `fetchRange:(NSRange)` is another option, location for the offset and length for the limit.

**Comment by jwatson** [comment]
Any thoughts @dostrander? If this is useful then we should include it, but I'd like for the API to be as clean as we can make it.

**Comment by dostrander** [comment]
@jwatson I'll use @KingOfBrian's suggestion of `fetchRange:(NSRange)range`  and fix it up tomorrow morning for approval

**Pull request closed without merging**
